{
 "title": "HTTP Server Projeto Korp",
 "tags": [
  "korp",
  "devops",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do serviço",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "http_server_projeto_korp_up" }
   ]
  },
  {
   "title": "Volume de requisições",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Requisições ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 16, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  }
 ]
}